### PR TITLE
Support result files from multiple race sessions

### PR DESCRIPTION
**Pull request by Timdpr**
Max 3 races for now. Test uses Automobilista. Also made practice session section style consistent with race and quali.

### CODE REVIEW

**Comment by mauserrifle** [comment]
Thanks! 

Could you extend the test case so it actually tests whether there are multiple race sessions? It now just tests the first session available. When done I'll merge :)

**Comment by Timdpr** [comment]
I'll come clean, I'm very unfamiliar with PHP so I was copying your test for multiple qualifying sessions without understanding it fully! I'm under the impression that rFactor/AMS etc generates seperate reports when you have multiple races, and I'm trying to handle the 'Race' element actually being 'Race2', etc. So would a test for multiple sessions be redundant or am I getting confused?

**Comment by mauserrifle** [comment]
My bad. Its OK as theres only one valid session in final result. Same as my qualify code it seems.

Sorry for delay. Merged!

**Comment by Timdpr** [comment]
No problem, glad it's working, cheers!

**Pull request merged**
